name: Terraform CI/CD

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./root

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Verify Azure Login
      - name: Check Azure Login
        run: az account show

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 5. Check Terraform Files
      - name: Check Terraform Files
        run: |
          pwd
          echo "Terraform files:"
          find . -name "*.tf" -type f

      # 6. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 7. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 8. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 9. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan
